### ISSUE TITLE
Clarification Request: Trust and Trustees

### ISSUE THREAD

**Issue by foundingnimo** [votem/proof-of-vote#10]
In page 19, the concept of trustee nodes in introduced, with a short discussion of the possible effects of collusion, and it is promised that

> trustee nodes operate in a high-governance environment. Special care is taken to ensure trustee nodes are likely to remain impartial, and that their security posture is appropriate to the task at hand.

This seems to be at odds with the following statement (page 23) 

> which is necessary as none of the trustees is trusted (otherwise we can just trust a trustee and do not need threshold decryption at all) and must be prevented from cheating

**Comment by phayes** [comment]
Both are true.  We don’t trust any one trustee, but we do trust them collectively.   Because of this an election authority will likely want to certify all trustees, but also only trust the collective group of trustees, and not any single trustee. 

Unlike consensus nodes, where voting power can be made proportional to risk and relative-trust, all trustees have the same “weight” and so should be governed accordingly.

**Comment by phayes** [comment]
@duckranger - does the above response answer your question?

**Comment by foundingnimo** [comment]
Yep cool
