### ISSUE TITLE
Clarification Request: White Paper, multiple votes

### ISSUE THREAD

**Issue by foundingnimo** [votem/proof-of-vote#17]
Page 32,
> If this is the case, validation only requires that there be no other Vote Transaction for this pseudonym for the current block.

In this case, won't it be theoretically possible for a voter to have time to change their vote, but if no other votes come in, the block containing first vote will not be added until election is finalized, thereby preventing the person from casting an override?

**Comment by jeffreypstern** [comment]
Because block creation will be a function of time rather than a specific block size. This will prevent long confirmation times in periods where few people are voting. Block creation will almost always use chronologically sequential transactions (with the exception of when there is network latency in transaction broadcasting) as there is no reward for block proposal.

**Comment by phayes** [comment]
Closing this issue. Please re-open if you feel this needs to be further addressed.
