### ISSUE TITLE
Clarification Request - White Paper - Mixing Nodes

### ISSUE THREAD

**Issue by foundingnimo** [votem/proof-of-vote#19]
Page 33
In the caption for figure 11 claims that a batch of messages to be shuffled is re-shuffled and re-encrypted by multiple nodes in the mix network. 

- The rest of the text in the page does not repeat this claim (so it's only in the caption of the figure)
- I think an explanation of why this is done (if it is done) needs to be provided. As it currently reads, there is no good reason to run the same operation through multiple mix-nodes, as a single mix-node should suffice to re-encrypt and shuffle the vote, and provide a ZKP.
- If every mix node handles every transaction- wouldn't there be a possibility for a rogue node to affect all of the votes (instead of affecting only a portion of them)?

**Comment by jeffreypstern** [comment]
You are correct in saying that a single mix-node _should_ suffice to re-encrypt and shuffle (with corresponding ZKP), assuming one honest mixing node, for complete anonymization.  However, by using multiple mix nodes, we prevent a single point of trust. 

The purpose of the mixnet here is to provide full anonymity to the voter. If the Authentication servers were to be compromised, one would theoretically be able to tie the voter to their encrypted vote through their pseudonym. Anonymity is provided by performing the following operations: 

- Each mix node shuffles and re-encrypts the votes, providing a proof of valid mix. 
- Providing a proof of valid mix mathematically guarantees that the post-shuffle votes are equivalent to pre-shuffle.
- While the mix node cannot change the value of the votes themselves ( because it must provide a proof of valid shuffle ), it can potentially store the order of the shuffle to break the anonymity of the voter (hence by using multiple nodes, we prevent a single point of trust)

**Comment by phayes** [comment]
Thanks for catching this. 

This is an error left over from an earlier version of the paper.  We can originally included a description of running multiple mixnets for a set of votes in order to protect against the possibility that our ZKP formulation or implementation was in error in some way.  It was part of a “defence-in-depth” approach to protect against the possibility that our ZKP folumation was vulnerable and that a mixer could modify votes by producing a fake ZKP. 

In the end we abandoned it for not being “cooked” enough, but this little reference to it slipped through.   We may introduce the multi-mix net-scheme at a later point when we feel more confident in its formulation and impact.

**Comment by foundingnimo** [comment]
Ok - I think this should be explained somewhat better in the paper.

**Comment by jeffreypstern** [comment]
Added in this description to the paper.
