### ISSUE TITLE
Clarification Request - Software Independence

### ISSUE THREAD

**Issue by foundingnimo** [votem/proof-of-vote#23]
Page 36
I feel like the category of Software Independence might not be aptly named. It is not immediately clear to me how the concern raised relates to software independence.
On a separate note, it is not immediately clear how the consideration of the protocol for the Software Independence concern raised actually addresses the concern. This makes sense if this concern is with the blockchain software itself - which is also unclear (as all nodes should share same code) - but I can't see from the explanation how, if an error occurs in the voting software itself (ie the software on the user's device) - the use of blockchain mitigates that.

**Comment by phayes** [comment]
Thank you for this.  I’ll try to explain here and then update the white paper to add more clarity.  

The assumption is that in a mature Proof-of-Vote system, not all blockchain nodes would be running the same software.  They would all be running the same protocol (so that they interoperate and the system functions), but ideally the entire blockchain network would be running a heterogenous set of protocol implementations.   As an example, some nodes might run a Java-based version, some might run a Rust-based version, and some might run a Go-based version.  They would all work together on the blockchain, but having different implementations of the same protocol ensures protocol robustness and implementations free of bugs.

**Comment by foundingnimo** [comment]
Looking forward to see it explained in the White Paper.

**Comment by jeffreypstern** [comment]
@phayes - added to the whitepaper.
