### ISSUE TITLE
Clarification Request: White Paper- Collection Accountability

### ISSUE THREAD

**Issue by foundingnimo** [votem/proof-of-vote#25]
Page 38

The paper posits that voters can detect that their vote has not been collected, and say that it is trivial for a voter to show that a vote transaction with their pseudonym is not present on the blockchain. 
Does this not cover the case of when a voter is allowed to vote multiple times? In this scenario, a voter can not show that their vote is not on the blockchain, if an older vote is already there.

**Comment by jeffreypstern** [comment]
You are correct. What the protocol has that would address this issue - denotated _Revocation Transactions_ - does not currently extend to scenarios where repeat/multiple voting is permissible. This is predominantly because of the rules and regulations governing American elections where such voting is prohibited; as a result, we did not really address this form of voting. 

With that, we do intend to extend the scope of _Revocation Transactions_ to allow for spoilage of votes post-vote-casting in the scenario where repeat voting is allowed (like in Estonia for example).

**Comment by jeffreypstern** [comment]
Building on that, we did construct it so that no other Vote Transaction exists for a given voter's pseudonym. However, some elections may allow for multiple Vote Transactions per voter, with only the last one being tallied. If this is the case, validation only requires that there be no other Vote Transaction for this pseudonym for the current block...You brought up some other concerns though related to this in issue #17 which we'll address there.

**Comment by foundingnimo** [comment]
Thanks for the clarification!

**Comment by phayes** [comment]
Closing this issue. Please re-open if you feel this needs to be further addressed.
