### ISSUE TITLE
Clarification Request: White Paper

### ISSUE THREAD

**Issue by foundingnimo** [votem/proof-of-vote#4]
Page 11, Step 7

It is not immediately clear how the system, when delivering an unmarked ballot, knows which election's public key to deliver back to the user.

**Comment by jeffreypstern** [comment]
There should never arise any ambiguity about which election is in question because election definitions do not transcend multiple elections. Similarly, voters (pseudonyms) do not transcend multiple elections, but are instead tied to one election definition. This means that when voters are delivered information, it is information only from the election that they are tied to.

I believe you might be asking about something else though - by "election's public key", are you referring to the specific geographically (or some other factor) defined ballot style that a given voter should receive ? If that is the case, this is addressed first through _Election Creation_ transactions where _Ballot Style IDs_ are created and later accomplished in full via _Authorization (Step 5)_, where authenticated voters are assigned their corresponding _Ballot Style ID_ so that in Step 7 -- the piece you have called out -- authenticated and authorized voters actually receive the correct unmarked ballot. 

If this does't address what you were asking @duckranger , please let me know!

**Comment by foundingnimo** [comment]
Yep all good

**Comment by phayes** [comment]
Closing this issue. Please re-open if you feel this needs to be further addressed.
